---
name: Parse-DMIDecode
version: 0.00
author:
  - Nicola Worthington <nicolaw@cpan.org>
abstract: Interface to SMBIOS under Linux using dmidecode
license: open_source
requires:
  Carp: 0
recommends:
  File::Which: 0.05
  Test::Deep: 0.093
  Test::Pod: 1.2
  Test::Pod::Coverage: 1.06
build_requires:
  Test: 0
  Test::More: 0
provides:
  Parse::DMIDecode:
    file: lib/Parse/DMIDecode.pm
    version: 0.00
generated_by: Module::Build version 0.2611
